service: service-top
runtime: php55
api_version: 1
threadsafe: true
instance_class: F1

skip_files:
- bin/
- test/
- ^composer.json$
- ^composer.json.lock$
- ^.*.bak$
- ^.*.swp$

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.95
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /login
  script: public/index.php
  secure: always
  login: required
  auth_fail_action: redirect

- url: /.*
  script: public/index.php
  secure: always
#  login: required
#  auth_fail_action: redirect

error_handlers:
  - file: public/default_error.html

